### ISSUE TITLE
Website now is unable to work as before.

### ISSUE THREAD

**Issue by wai2016** [ust-helloworld/The-Avengers-forming#12]
- No login function.
- Have some duplicate libraries.
- index.html is unable to link to other website.
- Some website is not used.
I am now working on the index.html and add back the login function.
Or in fact will we have a new login page?
Then I will just a simple button for debugging.

**Comment by robbieyang** [comment]
I think it is a bit early to merge the UI to helloworld without linking features. It needs time to fix it.
Katrina is working on login UI page, you should discuss how to directly apply log in function to the UI with Katrina.

**Comment by wai2016** [comment]
OK and I have finished fixing the index.html. #13 
Other html like profile is going to be added to corresponding html within tomorrow.

**Comment by wai2016** [comment]
Oh, I find out that there is a login page in #10 but it has conflict. Should we fix that conflict first?

**Comment by wai2016** [comment]
Fixed without using new login page.
