### ISSUE TITLE
Unit test - issue related to describe and it

### ISSUE THREAD

**Issue by RaymondWongCH** [ust-helloworld/The-Avengers-forming#26]
Setting up test cases, I discover that if I have too much "describe" and "it" in unit test files, I will encounter error "some of your tests did a full page reload!". Right now, the unit test files I raised in pull request do not have such error. However, I am afraid that when there are more functions later and more test cases are needed, this issue occurs again. Do you know why this happens?

**Comment by wai2016** [comment]
Solved
