### ISSUE TITLE
Improvement in member.js

### ISSUE THREAD

**Issue by wai2016** [ust-helloworld/The-Avengers-forming#35]
I find out that there is no create member function in member.js. Creating member is in fact using `savefunc()`. Therefore, I can't check whether the member exist or not, and this problem created the issue #33 .

Although, I can solve the problem #34 . The code is not beautiful.

Should we add a create member function or ignore this problem?

**Comment by robbieyang** [comment]
I think create member will be done after the UI of member page is finalized.

**Comment by p-wong1124** [comment]
because Peter's base code is that
if a member go to an event and show his selections of groups,
then his record is saved with the selections.

If a member go to the member page and does not set his selection,
the system will not save his record into the event

**Comment by p-wong1124** [comment]
So I think we need to create the member record once a user joins a particular event.

And then we can solve some problems that raised by this. 😄

**Comment by wai2016** [comment]
Ok then I will create a function call createfunc() in member.js today.

**Comment by wai2016** [comment]
I think it is not necessary to write a createfunc() becasue what savefunc() do is deleting the old thing and adding the new one but not appending the existing one.
