### ISSUE TITLE
Too many pull request

### ISSUE THREAD

**Issue by wai2016** [ust-helloworld/The-Avengers-forming#36]
There are too many pull requests now.

Solution that I find out:

1. Accept the pull request as soon as possible
Leave comments about pull requests to show your opinion. So that we can accept the pull request as soon as possible.
If not, there will be conflicts late on.

2. Consider other workflow
Or we can change our flow to a better flow after accepting all pull requests.
If we decide to think of a better work flow, we should stop raising pull requests.

**Comment by p-wong1124** [comment]
We need to have better understanding on what we are working on 
And what aspect we need to have people to work on

In order to clear our concepts on what should be implement  :smile

**Comment by poonvanessa** [comment]
Yes. otherwise crash again!!!!

**Comment by wai2016** [comment]
Good to see that there are now only 3 pull requests.
