### ISSUE TITLE
Help me to merge the UI!!!

### ISSUE THREAD

**Issue by katrinako** [ust-helloworld/The-Avengers-forming#50]
#30

**Comment by poonvanessa** [comment]
![image](https://cloud.githubusercontent.com/assets/22042488/20305082/a5e3dd50-ab6e-11e6-813f-c2f6021fa574.png)

This helps.

**Comment by poonvanessa** [comment]
Use command line or nothing.

**Comment by katrinako** [comment]
you can use github app or using command line by asking Jacky or Peter

**Comment by wai2016** [comment]
Merged.
