### ISSUE TITLE
Does using merge can reduce the "always ahead" problem?

### ISSUE THREAD

**Issue by p-wong1124** [ust-helloworld/The-Avengers-forming#75]
As I encounter a problem that,
my repo is always 10-20 ahead of team repo.
And I suspect that using squash and merge will cause it, (as it might not  recognize the changes made between local repo and the team repo).
Does it help if we allow merge all commit?

**Comment by wai2016** [comment]
Merge could help I think.
But you have to solve all conflicts.

**Comment by p-wong1124** [comment]
OK I can use another master to replace this lol

在 wai2016 notifications@github.com，2016年11月23日 下午1:39寫到：

Merge could help I think
But you have to solve all conflicts.
